trigger:
  branches:
    include:
      - main  # You can change 'main' to your branch name

pool:
  name: Self-hosted for Quiz4  # Use your self-hosted agent pool here

steps:
  # Step 1: Use the .NET SDK
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.x'  # Replace with your desired .NET version
      installationPath: $(Agent.ToolsDirectory)/dotnet

  # Step 2: Restore the project's dependencies
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  # Step 3: Build the application
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'

  # Step 4: Publish the application to a staging directory
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: true
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

  # Step 5: Publish the build artifact
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: 'drop'
      publishLocation: 'Container'
